version: '3'

services:
  nomobg:
    build: .
    ports:
      - "8000:8000"  # FastAPI backend
      - "8501:8501"  # Streamlit frontend
    volumes:
      - nomobg_models:/app/app/u2net/model
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  nomobg_models:
    driver: local 