version: '3'

services:
  nomobg:
    build: .
    ports:
      - "8000:8000"  # FastAPI backend
      - "8501:8501"  # Streamlit frontend

    volumes:
      - nomobg_models:/app/u2net/model  # Mount to the canonical location
      - /home/ubuntu/tmp:/app/tmp
      - /home/ubuntu/pip_cache:/app/pip_cache
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  nomobg_models:
    driver: local 