version: '3'

services:
  nomobg:
    build: .
    ports:
      - "8000:8000"  # FastAPI backend
      - "8501:8501"  # Streamlit frontend

    volumes:
      - ~/nomobg/app/u2net/model:/app/u2net/model  # Direct bind mount to host directory
      - /home/ubuntu/tmp:/app/tmp
      - /home/ubuntu/pip_cache:/app/pip_cache
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

# Remove the named volume as we're using a direct bind mount
# volumes:
#   nomobg_models:
#     driver: local 